{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kube-node-lifecycle-labeller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "kube-node-lifecycle-labeller.name" . }}
    helm.sh/chart: {{ template "kube-node-lifecycle-labeller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-node-lifecycle-labeller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kube-node-lifecycle-labeller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end}}
