apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "kube-node-lifecycle-labeller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "kube-node-lifecycle-labeller.name" . }}
    helm.sh/chart: {{ template "kube-node-lifecycle-labeller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if .Values.updateStrategy }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
    {{- if and .Values.updateStrategy (eq .Values.updateStrategy "RollingUpdate") }}
    rollingUpdate:
      maxUnavailable: {{ default 1 .Values.maxUnavailable }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ template "kube-node-lifecycle-labeller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ template "kube-node-lifecycle-labeller.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.verbose }}
            - name: VERBOSE
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.spot.labels }}
            - name: SPOT_LABELS
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.spot.taints }}
            - name: SPOT_TAINTS
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.onDemand.labels }}
            - name: LABELS
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.onDemand.taints }}
            - name: TAINTS
              value: {{ . | quote }}
            {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
